### ISSUE TITLE
Typo in Stopping criterion of Algorithm

### ISSUE THREAD

**Issue by darentsai** [marziacremona/ProbKMA-FMD#3]
Dear Prof. Cremona

I'm reading your excellent work "**probKMA**" published on _Journal of Computational and Graphical Statistics_.

In Section 2.2 Algorithm, the description of "**Stopping criterion**"

<img width="599" alt="stop_criterion" src="https://github.com/marziacremona/ProbKMA-FMD/assets/36108216/fdea9fe9-0a11-4c4b-949d-d9f69b0007d8">

seems NOT to conform to the code you wrote

https://github.com/marziacremona/ProbKMA-FMD/blob/7302cba4203c379a66caf24d8a7fa0b4f31f3a56/ProbKMA-FMD_functions.r#L861-L864

To my understanding, `P_old` and `P_new` are both NxK matrices. You take `rowSums()` to the square root of their product, which means that the summation $\sum$ should be across $k=1$ to $K$ instead of across $i=1$ to $N$. Therefore, the manuscript should be revised as follows

<img width="599" alt="stop_criterion_revise" src="https://github.com/marziacremona/ProbKMA-FMD/assets/36108216/2d93a7e5-806f-4f0a-946c-2f1b59db3508">

According to the definition of [Bhattacharyya distance (wiki)](https://en.wikipedia.org/wiki/Bhattacharyya_distance), the summation should be done on the domain of $p_{k,i}$, i.e. $k=1,2,...,K$. So I think your code is right, and the manuscript needs to be revised.

Maybe all above are my misunderstanding! Thank you for any replies. This project is an outstanding work!

Best regards,

**Comment by marziacremona** [comment]
Dear Darren, 

Thank you for your interest in probKMA and for the remark. 
You are absolutely correct, in the paper we swapped k and i, while the code is correct. 

BTW, we are working on an R package which highly improves the computational performance of probKMA code! 

Regards, 

Marzia
